---

name: CI

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: yarn --frozen-lockfile --non-interactive --silent

      - name: Prettier
        run: yarn format-verify

  tests:
    name: Tests
    runs-on: ubuntu-latest
    env:
      CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'

      - name: Install dependencies
        run: yarn --frozen-lockfile --non-interactive --silent

      - name: Setup Code Climate test-reporter
        run: |
          wget https://codeclimate.com/downloads/test-reporter/test-reporter-0.7.0-linux-amd64
          chmod 755 ./test-reporter-0.7.0-linux-amd64

      - name: Run tests with coverage
        run: |
          ./test-reporter-0.7.0-linux-amd64 before-build
          yarn test --coverage
          ./test-reporter-0.7.0-linux-amd64 after-build

      - name: Build
        run: yarn build
