---

name: CI

on:
  push:
    branches:
      - '**'
      - '!main'

jobs:
  tests:
    name: Tests
    runs-on: ubuntu-latest
    env:
      CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          persist-credentials: false

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: yarn --frozen-lockfile --non-interactive --silent

      - name: Setup Code Climate test-reporter
        run: |
          wget https://codeclimate.com/downloads/test-reporter/test-reporter-0.7.0-linux-amd64
          chmod 755 ./test-reporter-0.7.0-linux-amd64

      - name: Run lefthook
        run: npx lefthook run pre-merge-commit

      - name: Run tests with coverage
        run: |
          ./test-reporter-0.7.0-linux-amd64 before-build
          yarn test --coverage
          ./test-reporter-0.7.0-linux-amd64 after-build

      - name: Build
        run: yarn build

      - name: Test Release
        env:
          NPM_TOKEN: ${{ secrets.NPM_RELEASE_TOKEN }}
          GIT_AUTHOR_NAME: '@dreams-enterprise-bot'
          GITHUB_TOKEN: ${{ secrets.DREAMS_ENTERPRISE_BOT_GH_TOKEN }}
        run: yarn semantic-release-test
