name: Release

on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
  GITHUB_NPM_TOKEN: ${{ secrets.GH_TOKEN }}

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14.x'

      - name: Install dependencies
        run: yarn --frozen-lockfile --non-interactive --silent

      - name: Run tests
        run: yarn test

      - name: Release
        run: yarn semantic-release
